import base64

# Much simpler - just a plain Python file, no obfuscation
plain_bypass = """# -*- coding: utf-8 -*-
# BumYT Bypass - Plain version
import os, sys, random, string, hashlib, logging, json, time

BANK_ID = "BIDV"
BANK_ACCOUNT = "8816144490"
BANK_ACCOUNT_NAME = "LE VAN DIEU"
PRICE_FOR_RENEWAL = 200000
PRICE_FOR_NEW_KEY = 220000
BONUS_DAYS = 30
THONG_BAO = "BYPASS ACTIVE"
_api_connected = True
_tx_callbacks = []

def register_tx_callback(cb): _tx_callbacks.append(cb)

logger = logging.getLogger('KeyVerify')
logger.setLevel(logging.INFO)
try:
    _log_path = os.path.join(os.path.dirname(sys.executable) if getattr(sys, 'frozen', False) else os.path.dirname(os.path.abspath(__file__)), '..', 'key_verify.log')
    _fh = logging.FileHandler(_log_path, encoding='utf-8')
    _fh.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
    logger.addHandler(_fh)
except: pass

def connect_sheets():
    logger.info("BYPASS: connect_sheets OK")
    global _api_connected; _api_connected = True
    return True, True

def get_computer_id():
    return "BYPASS-" + hashlib.md5(str(time.time()).encode()).hexdigest()[:12]

def format_price(p):
    try: return f"{int(p):,}".replace(",", ".")
    except: return str(p)

def generate_random_key(prefix="BYT", length=6):
    return prefix + "-" + "".join(random.choices(string.ascii_uppercase + string.digits, k=length))

def check_and_activate_key(key, a=None, b=None):
    logger.info(f"BYPASS: Key {key} auto-approved")
    return True, "Key hop le! (bypass)", "(vinh vien)"

def check_key_status(key_name):
    k = key_name.strip().upper() if key_name else ""
    return {"exists": True, "key": k, "project": "BumYT", "expiry": "vinh vien", "status": "active"}

def get_renew_qr(key_name): return {"error": "BYPASS"}
def get_create_qr(key_name=None): return {"error": "BYPASS"}
def watch_payment(c): pass
def start_background_polling(): return True

def get_help_info():
    return {"price_create": "220.000", "price_renew": "200.000", "bank_id": "BIDV",
            "bank_account": "8816144490", "bank_account_name": "LE VAN DIEU",
            "bonus_days": 30, "thong_bao": "BYPASS ACTIVE"}

def _call_api(action, params=None, method="GET", timeout=None):
    return {"success": True, "message": "OK", "expiry_info": "(vinh vien)"}
"""

# Base64 encode the entire file
b64_content = base64.b64encode(plain_bypass.encode('utf-8')).decode('utf-8')

bat_content = f"""@echo off
chcp 65001 >nul
title BumYT Bypass - Plain Version
echo ============================================
echo   BumYT License Bypass (PLAIN)
echo   Remove obfuscation - direct bypass
echo ============================================
echo.

set "TARGET=%~dp0BumYT\\_internal\\key_verify.py"
if not exist "%TARGET%" (
    echo ERROR: Khong tim thay %TARGET%
    pause
    exit /b 1
)

echo [*] Ghi file bypass (plain Python - no obfuscation)...
powershell -NoProfile -ExecutionPolicy Bypass -Command "[System.IO.File]::WriteAllBytes('%TARGET%', [System.Convert]::FromBase64String('%b64_content%'))"
if %errorlevel% equ 0 (
    echo [*] THANH CONG!
    echo [*] key_verify.py da duoc ghi de bang code plain
    echo [*] Khong con obfuscation base64 + lzma
    echo [*] NHAP KEY BAT KY DE DUNG!
) else (
    echo [*] THAT BAI!
)
pause
"""

with open(r'D:\BumYT\bypass_plain.bat', 'w', encoding='utf-8') as f:
    f.write(bat_content)

print("Generated bypass_plain.bat")
print(f"Base64 payload: {len(b64_content)} chars")
